services:
  - type: web
    name: lasu-web
    env: docker
    plan: free
    dockerfilePath: dspace-jspui/Dockerfile  # Correct path
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8080"
    healthCheckProtocol: HTTP
    healthCheckIntervalSeconds: 30
    healthCheckTimeoutSeconds: 5
    healthCheckRetries: 3
    healthCheckGracePeriodSeconds: 300

