services:
  - type: web
    name: lasu-web
    env: docker
    plan: free
    dockerfilePath: dspace-jspui/Dockerfile
    autoDeploy: true
    healthCheckPath: /
    healthCheckProtocol: HTTP
    healthCheckIntervalSeconds: 30
    healthCheckTimeoutSeconds: 30  # Increased timeout for startup
    healthCheckRetries: 5  # Increased retries
    healthCheckGracePeriodSeconds: 300  # Longer grace period to wait for Tomcat to be ready
    envVars:
      - key: PORT
        value: "8080"




